### ISSUE TITLE
Unable to use application.yml default 

### ISSUE THREAD

**Issue by campksk** [appujet/lavamusic#549]
I use application.yml from this repo. But when I use cannot play music

**Comment by LucasB25** [comment]
> I use application.yml from this repo. But when I use cannot play music

it’s totally normal you need a lavalink server 
one has a hosting to create it?

**Comment by campksk** [comment]
> > I use application.yml from this repo. But when I use cannot play music
> 
> it’s totally normal you need a lavalink server one has a hosting to create it?

Yes, I create hosting and connetted. But when I use command it cann't play music

**Comment by campksk** [comment]
https://github.com/appujet/lavamusic/assets/93171859/e0a9919e-30e8-4d8d-a5e4-7bcea097e828

**Comment by aScriptingOreo** [comment]
I'm having similar issues with both the specified lavalink version and the dev one. The bot seems to be doing it's job right but something in lavalink breaks:
´´´log
lvlk  | 2024-05-01T13:36:43.443Z ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of uxs_HYw_mLk
lvlk  |
lvlk  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
lvlk  |         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lvlk  |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lvlk  |         at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lvlk  | Caused by: java.lang.RuntimeException: no jsUrl found EID: 815ff9d2-8e97-4486-b388-70b40fd233e2, html<redacted>
lvlk  |         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:137) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:289) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.1.jar!/:na]
lvlk  |         ... 4 common frames omitted
lvlk  |
lvlk  | 2024-05-01T13:36:47.700Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version, client=127.0.0.1
´´´

I'm running both Lavamusic and Lavalink inside docker.

**Comment by LucasB25** [comment]
https://discord.gg/coders-942117923001098260
https://discord.com/channels/942117923001098260/1232296473673203772

**Comment by campksk** [comment]
Thank you. Now I can fix it by add lavaplayer-youtube-source plugin.
